### ISSUE TITLE
Parent process runs even faster than systemcall in WSL

### ISSUE THREAD

**Issue by mikecovlee** [libmozart/system#6] opened 2020-02-21 07:30 UTC
Refer to #5 
We tested this feature in [covscript binding](https://github.com/covscript/covscript-process)

**Comment by mikecovlee** [comment] 2020-02-21 07:31
比  香  港  记  者  跑  得  还  快

**Comment by imkiva** [comment] 2020-02-21 07:38
笑 死 我 了

**Comment by imkiva** [comment] 2020-02-21 07:42
Reproduce code:
```covscript
import process
var p = process.exec("cs", {"-s"})
var ts = runtime.time()
p.in().println("runtime.info();runtime.delay(2000);system.exit(0)")
loop; until p.has_exited()
system.out.println("Time elapsed: " + (runtime.time() - ts))
system.out.println("")
var in = p.out()
while in.good() 
    var ch = in.get()
    if in.eof()
        break
    end
    system.out.put(ch)
end
system.out.println("")
system.out.println(p.has_exited() ? "Process has exited" : "Process not exited yet")
system.out.println("Process exited with code " + p.wait())
```

Run it using covscript command, got nothing but an exit status of 141.

**Comment by imkiva** [comment] 2020-02-21 07:42
The the gdb says it's a `SIGPIPE`, which means `manipulating a broken pipe`:

![TIM图片20200221154131](https://user-images.githubusercontent.com/9902643/75014203-bd069280-54c0-11ea-96e4-156c486fe0d7.png)

**Comment by imkiva** [comment] 2020-02-21 07:47
It seems that this bug only happens on WSL, and it's because WSL1 is too slow.

Here is what I suppose:

This is a traditional `fork() + exec()` style of launching a child process. We used a communication pipe (`close-on-exec` flag was set) to tell the parent process the `errno` after **execve returned** (or `EOF` if execve doesn't return).

Kernel will close this close-on-exec pipe on which the parent waits, but WSL1 is just to slow that **when the kernel just closed the pipe, our parent process returned, and even returned to the covscript to continue executing the line `p.in().println(...)`, but at this point the kernel has not completed the syscall of execve, that is, the kernel has not actually started the child process (such as doing load works etc.)**

I also tested the code on macOS and Ubuntu 18.04, and they worked very well.

**Closed as completed** 2020-02-22 07:40 UTC
Labels: bug, xswl
